# Generated by Django 5.2.5 on 2025-11-12 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('permalink', models.URLField()),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reddit Post',
                'verbose_name_plural': 'Reddit Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('permalink', models.URLField()),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.redditpost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Amigable'), ('informative', 'Informativo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reddit_reply_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='dashboard.comment')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
