# Generated by Django 5.2.8 on 2025-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reddit_images/'),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='is_own_post',
            field=models.BooleanField(default=False),
        ),
    ]
