# Generated by Django 5.2.8 on 2025-11-12 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_redditpost_image_redditpost_is_own_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('author_channel_id', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reply', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YouTube Comment',
                'verbose_name_plural': 'YouTube Comments',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Amigable'), ('informative', 'Informativo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_reply_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_response', to='dashboard.youtubecomment')),
            ],
            options={
                'verbose_name': 'YouTube Response',
                'verbose_name_plural': 'YouTube Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='youtubecomment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_comments', to='dashboard.youtubevideo'),
        ),
    ]
